### ISSUE TITLE
Work only on localhost not work public 

### ISSUE THREAD

**Issue by gillommnathony** [aeongdesu/fembed-video-api#2]
``Work only on localhost not work public

**Comment by aeongdesu** [comment]
Can you explain more? all of api or just stream video?

**Comment by gillommnathony** [comment]
> Can you explain more? all of api or just stream video?

Cannnot Stream video

**Comment by mdroidhd** [comment]
is there any way to fix the error?

**Comment by aeongdesu** [comment]
sorry! I don't have time to fix the issue because of personal problems 😔

I think preview site(fapi.deta.dev) have memory & storage limit, that's why you can't use stream video feature.

**Comment by aeongdesu** [comment]
moved to repl.it, because of serverless limitations
https://fembed.aeong.one/
