### ISSUE TITLE
can play only localhost

### ISSUE THREAD

**Issue by bondan20** [aeongdesu/fembed-video-api#9]
how to play video sir?
because only play in localhost

**Comment by aeongdesu** [comment]
It works for me, where do you host it?
![](https://nyan.shx.gg/5FRt6botm.png)

**Comment by bondan20** [comment]
instal in ubuntu,succes show api etc.
but, i try open url video,show like this[
![image](https://user-images.githubusercontent.com/47920163/187029485-4873e75a-205f-417f-a4e9-2893025d910c.png)
](url)

**Comment by bondan20** [comment]
can i contact u sir

**Comment by aeongdesu** [comment]
you should check documentation
![](https://nyan.shx.gg/5FW4DTjKp.png)
ex) https://fembed.aeong.one/qgl1-fee-e-nrry/video/1080

**Comment by bondan20** [comment]
hahahahhaa,, FINISH,, thx for info sir.
now,video can play :D
video play use bandwith VPS, so if i use this, i must use vps with fast speed.
# thx very much


sir,try another server please
req: StreamSb :D

**Comment by aeongdesu** [comment]
i dont want to support other servers, sorry!
